server:
  port: 8081
#  servlet:
#    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book
    username: root
    password: Howard0415
  thymeleaf:
    mode: HTML
  devtools:
    restart:
      trigger-file: .trigger
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
SavePath:
  ProfilePhoto: '/Users/waiting/IDEA/demo/src/main/resources/static/img/'
  ProfilePhotoMapper: '/img/'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.example.demo2: debug
  file:
    path: logs/devLog

