server:
  port: 8081
  servlet:
    context-path: /searchEngine
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weblist
    username: root
    password: Howard0415
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 100MB
SavePath:
  ProfilePhoto: '/Users/waiting/imgForClass/'
  ProfilePhotoMapper: '/imgForClass/'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    mode: HTML
logging:
  level:
    root: info
    com.example.datafinalproject: debug
  file:
    path: logs/devLog
